# Generated by Django 4.1 on 2022-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPlatforms',
            fields=[
                ('pf_name', models.CharField(max_length=255)),
                ('pf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pf_equity', models.BooleanField(default=True)),
                ('pf_forex', models.BooleanField(default=False)),
                ('pf_commodities', models.BooleanField(default=False)),
                ('pf_mutualfunds', models.BooleanField(default=False)),
                ('pf_international_markets', models.BooleanField(default=False)),
                ('pf_india_market', models.BooleanField(default=True)),
                ('pf_equity_intraday', models.BooleanField(default=False)),
                ('pf_equity_delivery', models.BooleanField(default=False)),
                ('pf_gtt_order', models.BooleanField(default=False)),
                ('pf_future_options', models.BooleanField(default=True)),
                ('pf_own_chart', models.BooleanField(default=True)),
                ('pf_thirdparty_chart_available', models.BooleanField(default=False)),
                ('pf_thirdparty_charts', models.CharField(blank=True, default='', max_length=255)),
                ('pf_loans', models.BooleanField(default=False)),
                ('pf_fixed_deposits', models.BooleanField(default=False)),
                ('pf_loan_rate', models.FloatField(blank=True, null=True)),
                ('pf_fd_rate', models.FloatField(blank=True, null=True)),
                ('pf_gold_bonds', models.BooleanField(default=False)),
                ('pf_ipo', models.BooleanField(default=True)),
                ('pf_charges_account_open', models.IntegerField(blank=True, default=1000)),
                ('pf_charges_amc', models.IntegerField(blank=True, default=1000)),
                ('pf_brokerage_equity_intraday1', models.IntegerField(blank=True, default=20)),
                ('pf_brokerage_equity_intraday2', models.FloatField(blank=True, default=0.5)),
                ('pf_brokerage_equity_delivery1', models.IntegerField(blank=True, default=20)),
                ('pf_brokerage_equity_delivery2', models.FloatField(blank=True, default=0.5)),
                ('pf_brokerage_fo', models.FloatField(blank=True, default=1000)),
                ('pf_brokerage_mf', models.FloatField(blank=True, default=1000)),
                ('pf_create_date', models.DateField(auto_now_add=True, null=True)),
                ('pf_last_update', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
